'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating personalized responses based on user input.
 *
 * - generatePersonalizedResponse - A function that takes user input and returns a personalized response.
 * - PersonalizedResponseInput - The input type for the generatePersonalizedResponse function.
 * - PersonalizedResponseOutput - The return type for the generatePersonalizedResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizedResponseInputSchema = z.object({
  userInput: z.string().describe('The user input to personalize the response to.'),
});
export type PersonalizedResponseInput = z.infer<
  typeof PersonalizedResponseInputSchema
>;

const PersonalizedResponseOutputSchema = z.object({
  personalizedResponse: z
    .string()
    .describe('The personalized response generated by the AI.'),
});
export type PersonalizedResponseOutput = z.infer<
  typeof PersonalizedResponseOutputSchema
>;

export async function generatePersonalizedResponse(
  input: PersonalizedResponseInput
): Promise<PersonalizedResponseOutput> {
  return personalizedResponseFlow(input);
}

const personalizedResponsePrompt = ai.definePrompt({
  name: 'personalizedResponsePrompt',
  input: {schema: PersonalizedResponseInputSchema},
  output: {schema: PersonalizedResponseOutputSchema},
  prompt: `You are a helpful chatbot designed to provide personalized responses based on user input.

  User Input: {{{userInput}}}

  Generate a response that is tailored to the user's specific needs and pain points, ensuring the conversation feels relevant and engaging.`,
});

const personalizedResponseFlow = ai.defineFlow(
  {
    name: 'personalizedResponseFlow',
    inputSchema: PersonalizedResponseInputSchema,
    outputSchema: PersonalizedResponseOutputSchema,
  },
  async input => {
    const {output} = await personalizedResponsePrompt(input);
    return output!;
  }
);
